#!/usr/bin/env python3
"""
Demonstration script showing the differences between the two agent implementations.
This script explains the architecture and flow of each agent.
"""

def demonstrate_simple_agent():
    """Explain the simple agent architecture."""
    print("🤖 SIMPLE AGENT (simple_agent)")
    print("=" * 50)
    print("📊 Architecture:")
    print("   Entry Point: agent")
    print("   Nodes: agent, action")
    print("   Flow: agent → action → agent → END")
    print()
    print("🔄 Execution Flow:")
    print("   1. agent: Calls model with tools bound")
    print("   2. Conditional routing:")
    print("      - If tool_calls present → action")
    print("      - If no tool_calls → END")
    print("   3. action: Executes tool calls")
    print("   4. action → agent (loop back)")
    print()
    print("🛠️  Available Tools:")
    print("   - Tavily Search (web search)")
    print("   - Arxiv Tool (academic papers)")
    print("   - RAG Tool (local PDF documents)")
    print()
    print("💡 Key Features:")
    print("   ✅ Simple tool-using agent")
    print("   ✅ Conditional tool calling")
    print("   ✅ Automatic tool execution")
    print("   ✅ Loop until no more tools needed")
    print()

def demonstrate_helpful_agent():
    """Explain the agent with helpfulness architecture."""
    print("🤖 AGENT WITH HELPFULNESS (agent_with_helpfulness)")
    print("=" * 50)
    print("📊 Architecture:")
    print("   Entry Point: agent")
    print("   Nodes: agent, action, helpfulness")
    print("   Flow: agent → action/helpfulness → agent → END")
    print()
    print("🔄 Execution Flow:")
    print("   1. agent: Calls model with tools bound")
    print("   2. Conditional routing:")
    print("      - If tool_calls present → action")
    print("      - If no tool_calls → helpfulness")
    print("   3. action: Executes tool calls")
    print("   4. helpfulness: Evaluates response quality")
    print("   5. helpfulness decision:")
    print("      - 'Y' (helpful) → END")
    print("      - 'N' (not helpful) → agent (continue)")
    print("      - Loop limit (10 iterations) → END")
    print()
    print("🛠️  Available Tools:")
    print("   - Tavily Search (web search)")
    print("   - Arxiv Tool (academic papers)")
    print("   - RAG Tool (local PDF documents)")
    print()
    print("💡 Key Features:")
    print("   ✅ Same tool capabilities as simple agent")
    print("   ✅ Helpfulness evaluation node")
    print("   ✅ Quality control loop")
    print("   ✅ Loop protection (max 10 iterations)")
    print("   ✅ Separate evaluation model (gpt-4.1-mini)")
    print()

def compare_agents():
    """Compare the two agent implementations."""
    print("🔍 AGENT COMPARISON")
    print("=" * 50)
    print()
    print("📊 SIMPLE AGENT vs HELPFUL AGENT:")
    print()
    print("🔄 Flow Differences:")
    print("   Simple Agent:")
    print("     agent → action → agent → END")
    print("     (stops when no more tools needed)")
    print()
    print("   Helpful Agent:")
    print("     agent → action/helpfulness → agent → END")
    print("     (stops when helpful OR no more tools)")
    print()
    print("🎯 Decision Points:")
    print("   Simple Agent:")
    print("     - Tool calls present? → Continue")
    print("     - No tool calls? → End")
    print()
    print("   Helpful Agent:")
    print("     - Tool calls present? → Execute tools")
    print("     - No tool calls? → Evaluate helpfulness")
    print("     - Helpful? → End")
    print("     - Not helpful? → Continue (with limit)")
    print()
    print("🛡️  Safety Features:")
    print("   Simple Agent:")
    print("     - No explicit loop protection")
    print("     - Relies on model to stop calling tools")
    print()
    print("   Helpful Agent:")
    print("     - Loop limit: 10 iterations")
    print("     - Explicit helpfulness evaluation")
    print("     - Quality control mechanism")
    print()

def show_usage_examples():
    """Show usage examples for both agents."""
    print("📝 USAGE EXAMPLES")
    print("=" * 50)
    print()
    print("🔧 Simple Agent Usage:")
    print("   curl -X POST http://localhost:2024/runs/stream \\")
    print("     -H 'Content-Type: application/json' \\")
    print("     -d '{")
    print('       "assistant_id": "simple_agent",')
    print('       "input": {')
    print('         "messages": [')
    print('           {')
    print('             "role": "human",')
    print('             "content": "What is the latest research on transformers?"')
    print('           }')
    print('         ]')
    print('       }')
    print('     }')
    print()
    print("🔧 Helpful Agent Usage:")
    print("   curl -X POST http://localhost:2024/runs/stream \\")
    print("     -H 'Content-Type: application/json' \\")
    print("     -d '{")
    print('       "assistant_id": "agent_with_helpfulness",')
    print('       "input": {')
    print('         "messages": [')
    print('           {')
    print('             "role": "human",')
    print('             "content": "Explain quantum computing in simple terms"')
    print('           }')
    print('         ]')
    print('       }')
    print('     }')
    print()

def main():
    """Main demonstration function."""
    print("🚀 LangGraph Agent Demonstration")
    print("=" * 60)
    print()
    
    # Demonstrate each agent
    demonstrate_simple_agent()
    demonstrate_helpful_agent()
    
    # Compare agents
    compare_agents()
    
    # Show usage examples
    show_usage_examples()
    
    print("🎉 Demonstration Complete!")
    print()
    print("🔗 Next Steps:")
    print("   1. Configure API keys in .env file")
    print("   2. Test with: uv run test_served_graph.py")
    print("   3. Open Studio: https://smith.langchain.com/studio?baseUrl=http://localhost:2024")
    print("   4. Compare the two agents in Studio")
    print()
    print("📚 Key Learnings:")
    print("   - Simple agent: Direct tool usage")
    print("   - Helpful agent: Quality control with evaluation")
    print("   - Both use the same tool set")
    print("   - Helpful agent has better safety features")

if __name__ == "__main__":
    main()
